# Generated by Django 3.1 on 2020-08-24 10:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cats_hedgehogs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bid',
            old_name='user',
            new_name='owner',
        ),
        migrations.RenameField(
            model_name='lot',
            old_name='user',
            new_name='owner',
        ),
        migrations.AlterField(
            model_name='lot',
            name='start_price',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
