# Generated by Django 3.1 on 2020-08-26 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cats_hedgehogs', '0002_auto_20200824_1035'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='accepted',
            field=models.BooleanField(default=False),
        ),
    ]
